import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import type { AxiosError } from 'axios'
import { ArrowLeft, ShieldAlert, UserX } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { Link, useParams } from 'react-router-dom'

import { EmptyState } from '@/components/shared/EmptyState'
import { LoadingSpinner } from '@/components/shared/LoadingSpinner'
import { PatientSummary } from '@/components/shared/PatientSummary'
import { useAuth } from '@/hooks/useAuth'
import { patientsApi } from '@/lib/api'
import { cn } from '@/lib/utils'
import { AppointmentsTab } from '@/pages/patients/profile/AppointmentsTab'
import { BillingHistoryTab } from '@/pages/patients/profile/BillingHistoryTab'
import { DemographicsTab } from '@/pages/patients/profile/DemographicsTab'
import { InvoicesTab } from '@/pages/patients/profile/InvoicesTab'
import { LabResultsTab } from '@/pages/patients/profile/LabResultsTab'
import { MedicalRecordsTab } from '@/pages/patients/profile/MedicalRecordsTab'

type TabKey = 'medicalRecords' | 'appointments' | 'demographics' | 'invoices' | 'billing' | 'labResults'

/**
 * `/patients/:patientId`. Sticky header (design-system.md/ui-brief.md) +
 * role-gated vertical tabs — see docs/psm2/sprint-3c-ui-overhaul.md's
 * expanded Screen 7 spec for exactly which tabs each role gets and why
 * (Invoices/Lab Results tabs are new, backed by invoicesController.js /
 * labResultsController.js). The backend intentionally returns a generic 404
 * for both "patient doesn't exist" and "exists but RLS says this doctor
 * isn't assigned to them" — those two cases are deliberately
 * indistinguishable here, matching the lookup page.
 *
 * "Invoices" and "Billing" are deliberately two separate tabs, not one:
 * Invoices (`patient_invoices`) is staff-uploaded scanned documents
 * (billing PDFs, consent forms); Billing (`visit_invoices`) is the real,
 * structured point-of-sale invoice generated by the visit-billing flow
 * (`pages/visits/`), with line items, VAT, and payment status. They're
 * unrelated tables with unrelated data — see DELTA-028 in report-delta.md.
 */
export default function PatientProfilePage() {
  const { patientId } = useParams<{ patientId: string }>()
  const { t } = useTranslation('patients')
  const { t: tCommon } = useTranslation('common')
  const { isAdmin, isDoctor } = useAuth()
  const [isEditing, setIsEditing] = useState(false)

  const {
    data: patient,
    isLoading,
    isError,
    error,
  } = useQuery({
    queryKey: ['patients', 'detail', patientId],
    queryFn: () => patientsApi.get(patientId!),
    enabled: !!patientId,
    retry: false,
  })

  const errorStatus = isError ? (error as AxiosError).response?.status : null

  const availableTabs = useMemo(() => {
    const tabs: TabKey[] = []
    if (isDoctor) tabs.push('medicalRecords')
    if (isDoctor || isAdmin) tabs.push('appointments', 'demographics')
    if (isDoctor || isAdmin) tabs.push('invoices', 'billing')
    if (isDoctor) tabs.push('labResults')
    return tabs
  }, [isDoctor, isAdmin])

  const [activeTab, setActiveTab] = useState<TabKey>(availableTabs[0] ?? 'demographics')
  const currentTab = availableTabs.includes(activeTab) ? activeTab : availableTabs[0]

  return (
    <div className="mx-auto flex max-w-[1280px] flex-col gap-6">
      <Link
        to="/patients"
        className="inline-flex w-fit items-center gap-1.5 text-sm font-medium text-primary-600 transition-colors duration-150 ease-out hover:text-primary-700"
      >
        <ArrowLeft className="h-4 w-4 rtl:rotate-180" aria-hidden="true" />
        {t('backToLookup')}
      </Link>

      {isLoading && <LoadingSpinner label={tCommon('loading')} />}

      {!isLoading && isError && errorStatus === 404 && (
        <EmptyState
          icon={UserX}
          title={t('profileErrors.notFoundTitle')}
          description={t('profileErrors.notFoundDescription')}
        />
      )}
      {!isLoading && isError && errorStatus === 403 && (
        <EmptyState
          icon={ShieldAlert}
          title={t('profileErrors.forbiddenTitle')}
          description={t('profileErrors.forbiddenDescription')}
        />
      )}
      {!isLoading && isError && errorStatus !== 404 && errorStatus !== 403 && (
        <p className="text-sm text-danger-600">{tCommon('error.generic')}</p>
      )}

      {!isLoading && !isError && patient && (
        <>
          <PatientSummary
            patient={patient}
            isEditing={isAdmin ? isEditing : undefined}
            onToggleEdit={isAdmin ? () => setIsEditing((v) => !v) : undefined}
          />

          <div className="grid grid-cols-1 gap-6 lg:grid-cols-[200px_1fr]">
            <nav className="flex flex-row gap-1 overflow-x-auto lg:flex-col lg:overflow-visible">
              {availableTabs.map((tab) => (
                <button
                  key={tab}
                  type="button"
                  onClick={() => setActiveTab(tab)}
                  className={cn(
                    'shrink-0 rounded-lg px-3 py-2 text-start text-sm font-medium transition-colors duration-150 ease-out',
                    'border-s-4 lg:border-s-4',
                    currentTab === tab
                      ? 'border-primary-600 bg-primary-50 text-primary-700'
                      : 'border-transparent text-muted-foreground hover:bg-neutral-100',
                  )}
                >
                  {t(`tabs.${tab}`)}
                </button>
              ))}
            </nav>

            <div className="rounded-lg border border-border bg-card p-5 shadow-card">
              {currentTab === 'medicalRecords' && <MedicalRecordsTab patientId={patient.patientId} />}
              {currentTab === 'appointments' && <AppointmentsTab patientId={patient.patientId} />}
              {currentTab === 'demographics' && (
                <DemographicsTab
                  patient={patient}
                  isAdmin={isAdmin}
                  isEditing={isAdmin && isEditing}
                  onDoneEditing={() => setIsEditing(false)}
                />
              )}
              {currentTab === 'invoices' && (
                <InvoicesTab patientId={patient.patientId} isAdmin={isAdmin} />
              )}
              {currentTab === 'billing' && <BillingHistoryTab patientId={patient.patientId} />}
              {currentTab === 'labResults' && <LabResultsTab patientId={patient.patientId} />}
            </div>
          </div>
        </>
      )}
    </div>
  )
}
