'use strict';

const ROLES = Object.freeze({
  SUPERADMIN: 'superadmin',
  DOCTOR: 'doctor',
  ADMIN: 'admin',
  PATIENT: 'patient',
});

const APPOINTMENT_STATUS = Object.freeze({
  SCHEDULED: 'scheduled',
  CONFIRMED: 'confirmed',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
});

const APPOINTMENT_TYPES = Object.freeze([
  'consultation',
  'follow_up',
  'emergency',
  'checkup',
]);

const AUDIT_ACTIONS = Object.freeze({
  LOGIN: 'LOGIN',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  ACCOUNT_LOCKOUT: 'ACCOUNT_LOCKOUT',
  CREATE_USER: 'CREATE_USER',
  DEACTIVATE_USER: 'DEACTIVATE_USER',
  REACTIVATE_USER: 'REACTIVATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  REGISTER_PATIENT: 'REGISTER_PATIENT',
  PATIENT_SELF_REGISTER: 'PATIENT_SELF_REGISTER',
  UPDATE_PATIENT: 'UPDATE_PATIENT',
  ASSIGN_DOCTOR: 'ASSIGN_DOCTOR',
  CREATE_RECORD: 'CREATE_RECORD',
  UPDATE_RECORD: 'UPDATE_RECORD',
  SCHEDULE_APPOINTMENT: 'SCHEDULE_APPOINTMENT',
  UPDATE_APPOINTMENT: 'UPDATE_APPOINTMENT',
  CONFIRM_APPOINTMENT: 'CONFIRM_APPOINTMENT',
  CANCEL_APPOINTMENT: 'CANCEL_APPOINTMENT',
});

const MAX_FAILED_LOGIN_ATTEMPTS = 3;

const JWT_COOKIE_NAME = 'token';

const PAGINATION = Object.freeze({
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
});

module.exports = {
  ROLES,
  APPOINTMENT_STATUS,
  APPOINTMENT_TYPES,
  AUDIT_ACTIONS,
  MAX_FAILED_LOGIN_ATTEMPTS,
  JWT_COOKIE_NAME,
  PAGINATION,
};
